apiVersion: v1
kind: List
metadata:
  name: cluster-config-list
  annotations:
    version: "1"
type: array
items:
  # Enforce the bootstraped resources
  - apiVersion: v1
    kind: Secret
    metadata:
      name: razee-cd-secrets
    type: Opaque
    data:
      # Enfoce this in an actual installation. Omit here from the public repo
      # LD_SDK_KEY: ZGF0YQ==
      # COS_SECRET_KEY: ZGF0YQ==
      # COS_KEY_ID: ZGF0YQ==
  - apiVersion: deploy.razee.io/v1alpha1
    kind: FeatureFlagSetLD
    metadata:
      name: default-ffsld
    spec:
      sdk-key:
        valueFrom:
          secretKeyRef:
            name: razee-cd-secrets
            key: LD_SDK_KEY
      identity: cluster-info
  - apiVersion: "deploy.razee.io/v1alpha1"
    kind: MustacheTemplate
    metadata:
      name: config-updater-mtp
    spec:
      custom-tags: ['<%', '%>']
      envFrom:
        - genericMapRef:
            apiVersion: "deploy.razee.io/v1alpha1"
            kind: FeatureFlagSetLD
            name: default-ffsld
      env:
        - name: cluster-type
          valueFrom:
            configMapKeyRef:
              name: "cluster-info"
              key: "type"
      templates:
        - apiVersion: "deploy.razee.io/v1alpha1"
          kind: RemoteResourceS3
          metadata:
            name: config-updater-rrs3
          spec:
            auth:
              hmac:
                access_key_id:
                  valueFrom:
                    secretKeyRef:
                      name: razee-cd-secrets
                      key: COS_KEY_ID
                secret_access_key:
                  valueFrom:
                    secretKeyRef:
                      name: razee-cd-secrets
                      key: COS_SECRET_KEY
            requests:
              - optional: true
                options:
                  url: https://raw.githubusercontent.com/razee-io/Razee-CD-Demo/master/deployment_with_boms/config/<%cluster-type%>/<%config%>/resources.yaml

  # Bill of Materials - list of microservices to deploy to the cluster
  - apiVersion: "deploy.razee.io/v1alpha1"
    kind: MustacheTemplate
    metadata:
      name: razee-bom-updater-mtp
    spec:
      custom-tags: ['<%', '%>']
      envFrom:
        - genericMapRef:
            apiVersion: "deploy.razee.io/v1alpha1"
            kind: FeatureFlagSetLD
            name: default-ffsld
      templates:
        - apiVersion: "deploy.razee.io/v1alpha1"
          kind: RemoteResourceS3
          metadata:
            name: microservice-bom-updater-rrs3
          spec:
            auth:
              hmac:
                access_key_id:
                  valueFrom:
                    secretKeyRef:
                      name: razee-cd-secrets
                      key: COS_KEY_ID
                secret_access_key:
                  valueFrom:
                    secretKeyRef:
                      name: razee-cd-secrets
                      key: COS_SECRET_KEY
            requests:
              - optional: true
                options:
                  url: https://raw.githubusercontent.com/razee-io/Razee-CD-Demo/master/deployment_with_boms/microservices/redis-master/<%redis-master%>/deploy.yaml
              - optional: true
                options:
                  url: https://raw.githubusercontent.com/razee-io/Razee-CD-Demo/master/deployment_with_boms/microservices/redis-slave/<%redis-slave%>/deploy.yaml
              - optional: true
                options:
                  url: https://raw.githubusercontent.com/razee-io/Razee-CD-Demo/master/deployment_with_boms/microservices/frontend/<%frontend%>/deploy.yaml
